### ISSUE TITLE
discuss alternatives

### ISSUE THREAD

**Issue by mojoaxel** [mozilla/sanitizer-polyfill#2]
We should discuss alternative xss-libraries:
- [xss-filters](https://github.com/YahooArchive/xss-filters) ⭐ 1k
- [xss](https://github.com/leizongmin/js-xss) ⭐ 4k
- [validators](https://github.com/validatorjs/validator.js#sanitizers) ⭐ 17.5k
- [dompurify](https://github.com/cure53/DOMPurify) ⭐ 7k
- [sanitize-html](https://github.com/apostrophecms/sanitize-html)⭐ 2.5k

![image](https://user-images.githubusercontent.com/600565/116422815-691fd800-a840-11eb-8786-a56252ac80af.png)
https://www.npmtrends.com/xss-filters-vs-xss-vs-dompurify-vs-sanitize-html-vs-validator

**Comment by mozfreddyb** [comment]
The README mentions that I'm in favor of using DOMPurify because it relies on the browser's parsing algorithm with the [NodeIterator](https://developer.mozilla.org/en-US/docs/Web/API/NodeIterator) API. Avoiding parser mismatches is crucial in the prevention of various kinds of XSS bugs. If the polyfill parsed oddly malformed HTML differently than the browser, it might emit HTML that the browser will then handle differently.

Of the libraries you listed, only DOMPurify seems to build upon a browser parsing API.
Specifically:

xss-filters: Archived and last commit was 2016? https://github.com/YahooArchive/xss-filters
xss: Uses its own HTML parser and does *not* rely on the browsers parser.
validator.js: Does not provide xss sanitization anymore, according to https://github.com/validatorjs/validator.js#xss-sanitization
sanitize-html: Same as xss, uses htmlparser2 does not use the browser parser.
