### ISSUE TITLE
`new Sanitizer() instanceof Sanitizer` should be true

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/sanitizer-polyfill#54]
Maybe I just didn't sleep well, but this is a bit mind-boggling.
The Sanitizer constructor should construct a Sanitizer object.

My endless admiration to the person who figures this one out :confounded:

**Comment by Bl4ck-h00d** [comment]
Can you explain to me what properties and methods should be there in it and how it is different from the current Sanitizer() constructor?

**Comment by mozfreddyb** [comment]
Looking at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof, it _seems_ to me, that `(new Sanitizer()) instanceof Sanitizher` should be easily true, but some code in polyfill.js is apparently incorrect.

I don't exactly know what the bug is, so this requires some research and might be tricky. (Maybe I'm also missing something really obvious, but I wouldn't count on that :))

**Comment by Bl4ck-h00d** [comment]
#55 Please review.

**Comment by 0xedward** [comment]
I think what we have is fine? I don't understand the problem here, but it's probably me just being an idiot :(

If we run the following code in devtools while on https://mozilla.github.io/sanitizer-polyfill/demo/:
```javascript
test = new Sanitizer(); // creates an instance of Sanitizer
differentSanitizer = new Sanitizer({allowElements: ['a']}); //creates a different instance of Sanitizer
test.getConfiguration(); //returns default configuration
differentSanitizer.getConfiguration(); // returns { "allowElements": [ "a" ] }
```

`test.getConfiguration()` returns a different result from `differentSanitizer.getConfiguration()` which seems to indicate they are different instances of Sanitizer

[MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#description) mention the following about `instanceof` and the following about the [object prototype chains](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain):
> The instanceof operator tests the presence of constructor.prototype in object's prototype chain.

> Nearly all objects in JavaScript are instances of Object which sits on the top of a prototype chain.

If we run the following code in devtools on the demo page:
```javascript
// Array
Array.prototype.constructor; // ƒ Array() { [native code] }
testArr = [0]
testArr.constructor //  ƒ Array() { [native code] }
Array instanceof Object // true
testArr instanceof Object // true

// Sanitizer
Sanitizer.prototype.constructor; // ƒ Sanitizer() { [native code] }
test.constructor // ƒ Sanitizer() { [native code] }

Sanitizer instanceof Object // true
new Sanitizer() instanceof Object // true
```

Since `Array` and `Sanitizer` exhibit the same behavior here, it seems like Sanitizer should return true for `new Sanitizer() instanceof Sanitizer`. So I tried evaluating `new Sanitizer() instanceof Sanitizer` in devtools while on the demo page and it does return true.

This is all a bunch of duck testing, but it seems like with what we have we can create instances of Sanitizer. Maybe devtools does some magic that makes these tests work, but when we evaluate `new Sanitizer() instanceof Sanitizer` in `polyfill.js` it fails?

**Comment by 0xedward** [comment]
Oh, nevermind! Ignore my last comment - I was being an idiot. This issue reproduces after I click the `¶` symbol and rerun the tests.

But we can still create Sanitizer instances, because Sanitizer has a constructor:
```javascript
Sanitizer.prototype.constructor // returns ƒ Sanitizer() { [native code] }
```

But it seems like the problem is, that instances of Sanitizer don't have a `constructor` in the Sanitizer object's prototype chain
```javascript
test = new Sanitizer();
test.prototype // doesn't contain constructor
test.prototype.constructor // throws Uncaught TypeError: Cannot read properties of undefined (reading 'constructor')

test instanceof Object // true
test instanceof Sanitizer // false, b/c test.prototype.constructor != Sanitizer.prototype.constructor
```

**Comment by mozfreddyb** [comment]
> I think what we have is fine? I don't understand the problem here, but it's probably me just being an idiot :(
> 

For the polyfill to be recognized by third-party scripts, I want to make sure that it feels and looks as close to the real thing as possible. Also, I'd like `sanitizeFor` and `setHTML` to test their parameter with "instance of Sanitizer" :)
